# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.x'
  inputs:
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '-r linux-x64 --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Webdrop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: Webdrop
  condition: succeededOrFailed()

- task: DeleteFiles@1
  displayName: 'Delete WEB Files'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)'
    Contents: '**'

- script: |
   dotnet tool install --global dotnet-ef
   dotnet-ef migrations script -i -o $(build.artifactstagingdirectory)\migrate.sql -p SBSClientManagement\SBSClientManagement.csproj
  displayName: 'Command Line Script'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: DataDb'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: DataDbdrop
  condition: succeededOrFailed()

- task: DeleteFiles@1
  displayName: 'Delete Data'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)'
    Contents: '**'
